# Generated by Django 5.0 on 2024-01-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/media/avatars/default_user_img.jpg', upload_to='media/avatars'),
        ),
    ]
